opt_out_usage
default_platform(:ios)

platform :ios do
  desc "create full xcframeworks"
  lane :xcframework do
    # Using custom xcargs causes create_xcframework to fail
    # but it still produces the xcframeworks so we ignore errors
    begin
      swift_protobuf_xcframework
    rescue
    end
    begin
      core_xcframework
    rescue
    end
  end

  desc "create wallet core xcframework"
  lane :core_xcframework do
    create_xcframework(
      workspace: 'TrustWalletCore.xcworkspace',
      scheme: 'WalletCore',
      destinations: ['iOS'],
      xcframework_output_directory: 'build',
      enable_bitcode: false,
      xcargs: "MACH_O_TYPE='staticlib'"
    )
  end

  desc "create swift protobuf xcframework"
  lane :swift_protobuf_xcframework do
    create_xcframework(
      workspace: 'TrustWalletCore.xcworkspace',
      scheme: 'SwiftProtobuf',
      destinations: ['iOS'],
      xcframework_output_directory: 'build',
      enable_bitcode: false,
      xcargs: "MACH_O_TYPE='staticlib'"
    )
  end
end
